### ISSUE TITLE
ftplib issue

### ISSUE THREAD

**Issue by jhagege** [PacktPublishing/Learning-Geospatial-Analysis-with-Python-Fourth-Edition#1]
Hi, great book thanks! 
Getting this error when running B19730_04_05-ftp.py script:

> ftplib.error_perm: 530 Anonymous sessions must use encryption.

**Comment by jhagege** [comment]
`# Read NOAA weather buoy location data via ftp
import ftplib
server = "ftp.pmel.noaa.gov"
dir = "taodata"
fileName = "taobuoypos.dat"
ftp = ftplib.FTP_TLS(server)

ftp.login()
ftp.prot_p()  # Set up secure data connection

ftp.cwd(dir)
with open(fileName, "wb") as out:
    ftp.retrbinary(f"RETR {fileName}", out.write)
    ftp.quit()
` seems to fix.

**Comment by GeospatialPython** [comment]
Excellent - thank you!

Joel Lawhead, PMP, GISP
*E-mail:* ***@***.***
*Web:* GeospatialPython.com <http://geospatialpython.com/>
*Twitter:* @SpatialPython
